---
title: "Walkthroughs"
author: "Ben Blanco"
date: "6/28/2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(readxl)
library(janitor)
```

# Walkthrough 1
```{r}
#Load data
gradebook <- 
  read_excel(
    here("data", "gradebooks", "ExcelGradeBook.xlsx"),
    sheet = 1, 
    skip = 10
  )

#Clean data using <janitor>
gradebook <- 
  gradebook %>%
  clean_names() %>%
  remove_empty() %>%
  select(-absent, -late)

#Create new dataframe for analysis
classwork_df <- 
  gradebook %>%
  select(2:9, contains("classwork_")) %>%
  mutate_at(vars(contains("classwork_")), list(~ as.numeric(.))) %>%
  pivot_longer(
    cols = contains("classwork_"),
    names_to = "classwork_number",
    values_to = "score"
  )
```
```{r}
#Analysis
summary(gradebook)

# Bar graph for categorical variable
gradebook %>%
  ggplot(aes(x = letter_grade,
             fill = running_average > 90)) +
  geom_bar() +
  labs(title = "Bar Graph of Student Grades",
       x = "Letter Grades",
       y = "Count",
       fill = "A or Better")

classwork_df %>%
  ggplot(aes(x = classwork_number,
    y = score,
    fill = classwork_number)) +
  geom_boxplot() +
  labs(title = "Distribution of Classwork Scores",
       x = "Classwork",
       y = "Score") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r}
#See if formative assessments are predicive of overall grade
#Check linearity
gradebook %>%
  ggplot(aes(x = formative_assessments,
             y = running_average)) +
  geom_point(color = "dark green") +
  geom_smooth(method = "lm") +
  labs(title = "Relationship between Formative Assessments and Grade Average",
       x= "Formative Assessment Score",
       y = "Overall Grade in Percentage")

#Check for outliers on independent variable
gradebook %>%
  ggplot(aes(x = "", #Use quotes to make sure that box plot is oriented with data on y-axis - indicates no data
             y = formative_assessments)) +
  geom_boxplot(fill = "dark green") +
  labs(x = "Formative Assessment",
       y = "Score")

#Check for outliers in dependent variable
gradebook %>%
  ggplot(aes(x = "", #Use quotes to make sure that box plot is oriented with data on y-axis - indicates no data
             y = running_average)) +
  geom_boxplot(fill = "dark orange") +
  labs(x = "Overall Score in Percentage",
       y = "Score")

#Run simple linear regreesion
reg1 <- lm(running_average ~ formative_assessments, data = gradebook )
summary(reg1)

#This is a SIMPLE linear regression with one variable --> we could probably explain more using other variables like HW
#Also -- this analysis is relational at BEST. There is no causal statements we can make and there are a lot of endogeneity issues. Particularly b/c the running average is constructed using scores on formatives, so there has to be a relationship....

#Would be more interesting to track types of interventions and supports and the grades of students?
```

#Walkthrough 2
```{r}
#Load data (scrapped from pdf)
race_pdf <- readRDS(here("data", "agg_data", "race_pdf.Rds"))

#Convert data to dataframe
race_df <-
  race_pdf %>%
  # Turn each page into a tibble
  map(~ as_tibble(.x, .name_repair = "unique")) %>% 
  # Make data frame and remove unnecessary rows
  map_df(~ slice(.,-1:-2)) %>%
  # Use descriptive column names
  set_names(
    c(
      "school_group",
      "school_name",
      "grade",
      "na_num", # Native American number of students
      "na_pct", # Native American percentage of students
      "aa_num", # African American number of students
      "aa_pct", # African American percentage
      "as_num", # Asian number of students
      "as_pct", # Asian percentage
      "hi_num", # Hispanic number of students
      "hi_pct", # Hispanic percentage
      "wh_num", # White number of students
      "wh_pct", # White percentage
      "pi_pct", # Pacific Islander percentage
      "blank_col",
      "tot" # Total number of students (from the Race PDF)
    )
  )

race_df2 <-
  race_df %>%
  # Remove unnecessary columns
  select(-school_group, -grade, -pi_pct, -blank_col) %>%
  # Filter to get grade-level numbers
  filter(str_detect(school_name, "Total"),
         school_name != "Grand Total") %>%
  # Clean up school names
  mutate(school_name = str_replace(school_name, "Total", "")) %>%
  # Remove white space
  mutate_if(is.character, trimws) %>%
  # Turn percentage columns into numeric and decimal format
  mutate_at(vars(contains("pct")), list( ~ as.numeric(str_replace(., "%", "")) / 100))

#Load more data 
frpl_pdf <- readRDS(here("data", "agg_data","frpl_pdf.Rds"))
frpl_df <- 
  frpl_pdf %>%
  map(~ as_tibble(.x, .name_repair = "unique")) %>% 
  # Make data frame and remove unnecessary rows
  map_df( ~ slice(.,-1)) %>% #WHY DO YOU NEED SLICE FUNCTION IN MAP_DF TO WORK? HOW DO YOU TURN PDF MATRIX --> DATAFRAME?
  set_names(
    c(
      "school_name",
      "not_eligible_num", # Number of non-eligible students,
      "reduce_num", # Number of students receiving reduced price lunch
      "free_num",   # Number of students receiving free lunch
      "frpl_num",  # Total number of students (from the FRPL PDF)
      "frpl_pct" # Free/reduced price lunch percentage
    )
  )

frpl_df2 <-
  frpl_df %>%
  filter(
    # Remove blanks
    school_name != "",
    # Filter out the rows in this list
    !school_name %in% c(
      "ELM K_08",
      "Mid Schl",
      "High Schl",
      "Alt HS",
      "Spec Ed Total",
      "Cont Alt Total",
      "Hospital Sites Total",
      "Dist Total"
    )
  ) %>%
  # Turn percentage columns into numeric and decimal format
  mutate(frpl_pct = as.numeric(str_replace(frpl_pct, "%", "")) / 100)

#Join datasets
joined_df <-
  left_join(race_df2, frpl_df2, by = c("school_name")) %>%
  mutate_at(2:17, as.numeric)

district_merged_df <-
  joined_df %>%
  # Calculate high poverty numbers
  mutate(
    hi_povnum = case_when(frpl_pct > .75 ~ hi_num),
    aa_povnum = case_when(frpl_pct > .75 ~ aa_num),
    wh_povnum = case_when(frpl_pct > .75 ~ wh_num),
    as_povnum = case_when(frpl_pct > .75 ~ as_num),
    na_povnum = case_when(frpl_pct > .75 ~ na_num)
  ) %>%
  adorn_totals() %>%
  # Create percentage by demographic
  mutate(
    na_pct = na_num / tot,
    aa_pct = aa_num / tot,
    as_pct = as_num / tot,
    hi_pct = hi_num / tot,
    wh_pct = wh_num / tot,
    frpl_pct = (free_num + reduce_num) / frpl_num,
    # Create percentage by demographic and poverty
    hi_povsch = hi_povnum / hi_num[which(school_name == "Total")],
    aa_povsch = aa_povnum / aa_num[which(school_name == "Total")],
    as_povsch = as_povnum / as_num[which(school_name == "Total")],
    wh_povsch = wh_povnum / wh_num[which(school_name == "Total")],
    na_povsch = na_povnum / na_num[which(school_name == "Total")]
  )

district_tidy_df <-
  district_merged_df %>%
  pivot_longer(
    cols = -matches("school_name"),
    names_to = "category",
    values_to = "value"
  )
```

